-- RealNames.lua
-- Stand script for GTA V Story Mode (Legacy).
-- Replaces in-game vehicle and weapon GXT labels with real-life names.
--
-- Original list: harleenquinzzel, thanks xm4ddy.
-- This rewrite drops the broken auto-updater (that was the soup.json.encode
-- crash and the 'unexpected symbol near end' error at the DCN warning).
-- Label keys are the game's gameName GXTs. Several models share one label.
--
-- Install: copy this file into Stand/Lua Scripts and run it.
-- Commands: rcn (cars on), rwn (weapons on), dcn / dwn (restore).

local SCRIPT_VERSION = "4.0.0"

local function clean_name(text)
    text = text or ""
    text = text:gsub(";", ",")
    text = text:gsub('"', "'")
    return text
end

local function apply_labels(entries)
    for i, data in ipairs(entries) do
        local key = data[1]
        local name = clean_name(data[2])
        if name == "" then
            name = " "
        end
        menu.trigger_commands("addlabel " .. key)
        menu.trigger_commands("edit" .. key .. " " .. name)
        if i % 10 == 0 then
            util.yield()
        end
    end
end

local function remove_labels(entries)
    for i, data in ipairs(entries) do
        menu.trigger_commands("remove" .. data[1])
        if i % 10 == 0 then
            util.yield()
        end
    end
end

local cars = {
    -- Hide fictional manufacturer prefixes. The car label already has the real name.
    -- EMPEROR is skipped here: that GXT is also the Cadillac DeVille sedan.
    { "ALBANY", "" },
    { "ANNIS", "" },
    { "BENEFAC", "" },
    { "BENEFACTOR", "" },
    { "BF", "" },
    { "BOLLOKAN", "" },
    { "BRAVADO", "" },
    { "BRUTE", "" },
    { "BUCKING", "" },
    { "CANIS", "" },
    { "CHARIOT", "" },
    { "CHEVAL", "" },
    { "CLASSIQUE", "" },
    { "COIL", "" },
    { "DECLASSE", "" },
    { "DEWBAUCH", "" },
    { "DINKA", "" },
    { "DUNDREAR", "" },
    { "ENUS", "" },
    { "FATHOM", "" },
    { "GALLIVAN", "" },
    { "GROTTI", "" },
    { "HIJAK", "" },
    { "HVY", "" },
    { "IMPONTE", "" },
    { "INVERTO", "" },
    { "JOBUILT", "" },
    { "KARIN", "" },
    { "KRAKEN", "" },
    { "LAMPADA", "" },
    { "LAMPADATI", "" },
    { "LCC", "" },
    { "MAIBATSU", "" },
    { "MAMMOTH", "" },
    { "MAXWELL", "" },
    { "MTL", "" },
    { "NAGASAKI", "" },
    { "OBEY", "" },
    { "OCELOT", "" },
    { "OVERFLOD", "" },
    { "PEGASSI", "" },
    { "PENAUD", "" },
    { "PFISTER", "" },
    { "PRINCIPL", "" },
    { "PROGEN", "" },
    { "RUNE", "" },
    { "SCHYSTER", "" },
    { "SHITZU", "" },
    { "SPEEDOPH", "" },
    { "STANLEY", "" },
    { "TOUNDRA", "" },
    { "TRUFFADE", "" },
    { "UBERMACH", "" },
    { "UBERMACHT", "" },
    { "VAPID", "" },
    { "VULCAR", "" },
    { "VYSSER", "" },
    { "WEENY", "" },
    { "WESTERN", "" },
    { "WILLARD", "" },
    { "ZIRCONIU", "" },

    -- Albany / Cadillac, Lincoln
    { "ALPHA", "Cadillac Cien Concept" },
    { "BRIGHAM", "Cadillac Miller-Meteor '59" },
    { "BTYPE2", "Munster Koach" },
    { "BUCCANEE", "Chevrolet Monte Carlo '70" },
    { "BUCCANEE2", "Chevrolet Monte Carlo (Custom)" },
    { "CAVALCADE3", "Cadillac Escalade-V '23" },
    { "CAVCADE", "Cadillac Escalade" },
    { "HERMES", "Mercury Eight '49" },
    { "LURCHER", "Funeral Coach" },
    { "MANANA", "Cadillac Eldorado '69" },
    { "MANANA2", "Cadillac Eldorado (Custom)" },
    { "PRIMO", "Cadillac Seville '92" },
    { "PRIMO2", "Cadillac Seville (Custom)" },
    { "ROOSEVELT", "Cadillac 341A Town Sedan '28" },
    { "ROOSEVELT2", "Cadillac 341A Town Sedan '28 (Valor)" },
    { "VIRGO", "Cadillac Eldorado '70" },
    { "VSTR", "Cadillac CTS-V '16" },
    { "WASHINGT", "Lincoln Town Car '98" },

    -- Annis / Nissan, Mazda
    { "DRIFTEUROS", "Nissan 370Z (Drift)" },
    { "DRIFTHARDY", "Nissan Laurel (C33) (Drift)" },
    { "DRIFTREMUS", "Nissan Silvia S13 (Drift)" },
    { "DRIFTZR350", "Mazda RX-7 (Drift)" },
    { "ELEGY", "Nissan Skyline GT-R (R32) '89" },
    { "ELEGY2", "Nissan GT-R (R35) '07" },
    { "EUROS", "Nissan 370Z (Z34) '08" },
    { "EUROSX32", "Nissan 300ZX (Z32) '89" },
    { "HARDY", "Nissan Laurel (C33)" },
    { "HELLION", "Nissan Patrol Safari (Y60) '89" },
    { "LE7B", "Mazda 787B '90" },
    { "MINIMUS", "Nissan Maxima (A36)" },
    { "R300", "Nissan Z (RZ34) '23" },
    { "REMUS", "Nissan Silvia (S13) '88" },
    { "S80", "Nissan R90C '91" },
    { "SAVESTRA", "Mazda RX-3 '73" },
    { "ZR350", "Mazda RX-7 (FD3S) '92" },
    { "ZR380", "Nissan 350Z (Z33) (Apocalypse)" },
    { "ZR3802", "Nissan 350Z (Z33) (Future Shock)" },
    { "ZR3803", "Nissan 350Z (Z33) (Nightmare)" },

    -- Benefactor / Mercedes-Benz
    { "BRUISER", "Mercedes-Benz W114/W115 (Apocalypse)" },
    { "BRUISER2", "Mercedes-Benz W114/W115 (Future Shock)" },
    { "BRUISER3", "Mercedes-Benz W114/W115 (Nightmare)" },
    { "DUBSTA", "Mercedes-Benz G-Class (W463)" },
    { "DUBSTA3", "Mercedes-Benz G63 AMG 6x6" },
    { "FELTZER", "Mercedes-Benz SL65 AMG Black Series" },
    { "FELTZER3", "Mercedes-Benz 300 SL" },
    { "GLENDALE", "Mercedes-Benz W123" },
    { "GLENDALE2", "Mercedes-Benz W123 (Custom)" },
    { "LIMO2", "Mercedes-Benz S 600 Pullman Guard (Armored)" },
    { "LM87", "Mercedes-Benz Sauber C9" },
    { "OPENWHEEL1", "Red Bull RB7" },
    { "PANTO", "Smart Fortwo" },
    { "SCHAFTER", "Mercedes-Benz S63 AMG W221" },
    { "SCHAFTER3", "Mercedes-Benz S65 AMG W221" },
    { "SCHAFTER4", "Mercedes-Benz S65 AMG W221 LWB" },
    { "SCHAFTER5", "Mercedes-Benz S65 AMG W221 (Armored)" },
    { "SCHAFTER6", "Mercedes-Benz S65 AMG W221 LWB (Armored)" },
    { "SCHWARZE", "Mercedes-Benz C63 AMG Coupe" },
    { "SERRANO", "Mercedes-Benz M-Class W164" },
    { "SM722", "Mercedes-Benz SLR McLaren Stirling Moss" },
    { "SURANO", "Mercedes-Benz SLS AMG" },
    { "XLS", "Mercedes-Benz GLS (X166)" },
    { "XLS2", "Mercedes-Benz GLS (X166)(Armored)" },

    -- Benefactor (alt label)
    { "DRIFTVORSCH", "Mercedes-Benz 500E (W124) (Drift)" },
    { "KRIEGER", "Mercedes-Benz AMG One" },
    { "SCHLAGEN", "Mercedes-Benz AMG GT" },
    { "STREITER", "Mercedes-Benz E400 All-Terrain 4x4" },
    { "TERBYTE", "Mercedes-Benz Zetros 6x6 Expedition Truck" },
    { "VORSCHLAG", "Mercedes-Benz 500E (W124)" },

    -- BF / Volkswagen
    { "BFINJECT", "Baja Bug" },
    { "BIFTA", "Meyers Manx" },
    { "CLUB", "Volkswagen Golf Mk1 (Type 17)" },
    { "DUNE", "Sandrail" },
    { "DUNE3", "Desert Patrol Vehicle (DPV)" },
    { "RAPTOR", "Campagna T-Rex" },
    { "SURFER", "Volkswagen Type 2" },
    { "SURFER2", "Volkswagen Type 2" },
    { "SURFER3", "Volkswagen Type 2 (Custom)" },
    { "WEEVIL", "Volkswagen Beetle" },
    { "WEEVIL2", "Volkswagen Beetle Rat Rod" },

    -- Bollokan / Hyundai
    { "ENVISAGE", "Hyundai N Vision 74" },
    { "PRAIRIE", "Hyundai Tiburon '02" },

    -- Bravado / Dodge
    { "BANSHEE", "Dodge Viper SRT-10 '03" },
    { "BANSHEE2", "Dodge Viper SRT-10 (Widebody)" },
    { "BANSHEE3", "Dodge Viper ACR '16" },
    { "BISON", "Dodge Ram 1500 '09" },
    { "BUFFALO", "Dodge Charger '06" },
    { "BUFFALO02", "Dodge Charger SRT8 '12" },
    { "BUFFALO3", "Dodge Charger SRT8 (Sprunk)" },
    { "BUFFALO4", "Dodge Charger SRT Hellcat '20" },
    { "BUFFALO5", "Dodge Charger Daytona SRT" },
    { "DLOADER", "Ford Model A Pickup" },
    { "DORADO", "Dodge Durango '97" },
    { "DRIFTGAUNTLET4", "Dodge Challenger Hellcat (Drift)" },
    { "GAUNTLET", "Dodge Challenger '08" },
    { "GAUNTLET2", "Dodge Challenger '08 RedWood" },
    { "GAUNTLET3", "Dodge Challenger '70" },
    { "GAUNTLET4", "Dodge Challenger SRT Hellcat" },
    { "GAUNTLET5", "Dodge Charger Daytona '69" },
    { "GAUNTLET6", "Dodge Challenger SRT TA2" },
    { "GREENWOOD", "Dodge Monaco '77" },
    { "GRESLEY", "Dodge Durango '10" },
    { "HALFTRACK", "M3 Half-Track" },
    { "MONSTER3", "Dodge W-Series '42 'Bigfoot' (Apocalypse)" },
    { "MONSTER4", "Dodge W-Series '42 'Bigfoot' (Future Shock)" },
    { "MONSTER5", "Dodge W-Series '42 'Bigfoot' (Nightmare)" },
    { "PARADISE", "Chevrolet Van Woodie" },
    { "POLBUFFALO", "Dodge Charger Pursuit" },
    { "POLBUFFALO6", "Dodge Charger STX (Police)" },
    { "POLDORADO", "Dodge Durango (Police)" },
    { "POLGAUNTLET", "Dodge Challenger SRT Demon Pursuit" },
    { "POLGREENW", "Dodge Monaco '77 (Police)" },
    { "RLOADER2", "Dodge W-Series '41" },
    { "RUMPO", "Chevrolet Express Van '96" },
    { "RUMPO3", "Sportsmobile Classic 4×4" },
    { "VERLIER", "TVR Sagaris" },
    { "YOUGA", "Dodge Ram Van '94" },
    { "YOUGA2", "Ford Econoline '68" },
    { "YOUGA3", "Ford Econoline E-300 Quadravan '74" },

    -- Brute / GMC
    { "BOXVILLE", "GMC Stepvan" },
    { "BOXVILLE6", "GMC Stepvan (LSDS)" },
    { "CAMPER", "Chevrolet Express G3500 '02" },
    { "PONY", "GMC Vandura '71" },
    { "STOCKADE", "International Navistar 4700" },
    { "STOCKADE4", "International 4700 (Bobcat)" },
    { "TACO", "GMC Stepvan" },
    { "TIPTRUCK", "Ford L8000 Dump Truck" },

    -- Buckingham / aircraft
    { "ALPHAZ1", "Sharp Nemesis NXT" },
    { "CARGOBOB5", "Sikorsky CH-53K King Stallion" },
    { "CONADA", "MD 902 Explorer" },
    { "CONADA2", "MD 969 Twin Attack" },
    { "HOWARD", "Hughes H-1 Racer" },
    { "LUXOR", "Learjet 45 (Private Jet)" },
    { "LUXOR2", "Learjet 45 Deluxe" },
    { "MILJET", "Bombardier CRJ200" },
    { "NIMBUS", "Cessna Citation X" },
    { "PYRO", "De Havilland Vampire" },
    { "SHAMAL", "Learjet 45" },
    { "SVOLITO", "Eurocopter EC145" },
    { "SVOLITO2", "Eurocopter EC145 Carbon" },
    { "SWIFT", "AgustaWestland AW109S Grand" },
    { "SWIFT2", "AgustaWestland AW109S Grand Deluxe" },
    { "VESTRA", "Cirrus Vision SF50" },
    { "VOLATUS", "Airbus Helicopters H155" },

    -- Canis / Jeep
    { "BODHI2", "Kaiser Jeep M715" },
    { "CASTIGATOR", "Jeep Wrangler Unlimited (JL)" },
    { "CRUSADER", "Jeep Wrangler (Military)" },
    { "FREECRAWLER", "Rezvani Tank" },
    { "KALAHARI", "Citroën Mehari" },
    { "KAMACHO", "Jeep Crew Chief 715 concept" },
    { "MESA", "Jeep Wrangler Unlimited" },
    { "POLTERMINU", "Jeep Wrangler (Police)" },
    { "SEMINOLE", "Jeep Grand Cherokee WJ" },
    { "SEMINOLE2", "Jeep Cherokee XJ" },
    { "TERMINUS", "Jeep Wrangler Rubicon (JL)" },

    -- Chariot
    { "ROMERO", "Cadillac Fleetwood Hearse" },

    -- Cheval / Holden
    { "FUGITIVE", "Holden Commodore (VE) '06" },
    { "MARSHALL", "Chevrolet El Camino 'Monster Truck'" },
    { "PICADOR", "Chevrolet El Camino '68" },
    { "SURGE", "Holden Volt '10" },
    { "TAIPAN", "Hennessey Venom F5" },

    -- Classique / Oldsmobile
    { "BROADWAY", "Oldsmobile 66 Club Sedan '46" },

    -- Coil / Tesla, Rimac
    { "BRAWLER", "Local Motors Rally Fighter" },
    { "CYCLONE", "Rimac Concept One" },
    { "CYCLONE2", "Rimac Nevera" },
    { "RAIDEN", "Tesla Model S" },
    { "VOLTIC", "Tesla Roadster '08" },
    { "VOLTIC2", "Tesla Roadster '08 Rocket" },

    -- Declasse / Chevrolet
    { "ASEA", "Chevrolet Aveo T300 '11" },
    { "BRUTUS", "Chevrolet K-2500 Silverado '88 (Apocalypse)" },
    { "BRUTUS2", "Chevrolet K-2500 Silverado '88 (Future Shock)" },
    { "BRUTUS3", "Chevrolet K-2500 Silverado '88 (Nightmare)" },
    { "BURRITO", "Chevrolet Express Van '96" },
    { "BURRITO2", "Chevrolet Express Van (Bugstars)" },
    { "DRAUGUR", "Chevrolet Offroad Concept" },
    { "DRIFTL352", "Chevrolet S-10 (Drift)" },
    { "DRIFTTAMPA", "Ford Mustang Hoonicorn (Drift)" },
    { "DRIFTYOSEM", "Ford F-150 Hoonitruck (Drift)" },
    { "GBURRITO", "Chevrolet Express Van (Gang)" },
    { "GBURRITO2", "Chevrolet Express Van (Gang)" },
    { "GRANGER", "Chevrolet Suburban (GMT900) '07" },
    { "GRANGER2", "Chevrolet Suburban '21" },
    { "HOTRING", "Chevrolet Lumina NASCAR '90" },
    { "IMPALER", "Chevrolet Impala Sport Coupe '67" },
    { "IMPALER2", "Buick Riviera '71 (Apocalypse)" },
    { "IMPALER3", "Buick Riviera '71 (Future Shock)" },
    { "IMPALER4", "Buick Riviera '71 (Nightmare)" },
    { "IMPALER5", "Chevrolet Impala SS '94" },
    { "IMPALER6", "Chevrolet Impala '80" },
    { "L35", "Chevrolet 3100 Pickup '53" },
    { "L352", "Chevrolet S-10 '91" },
    { "LGUARD", "Chevrolet Suburban (Lifeguard)" },
    { "MAMBA", "AC Cobra (MkIII) '65" },
    { "MOONBEAM", "Chevrolet Astro '85" },
    { "MOONBEAM2", "Chevrolet Astro '85 (Custom)" },
    { "OPENWHEEL2", "Dallara DW12" },
    { "POLIMPALER5", "Chevrolet Impala SS '94" },
    { "POLIMPALER6", "Chevrolet Impala '80" },
    { "PRANGER", "Chevrolet Astro '85 (Park Ranger)" },
    { "PREMIER", "Chevrolet Cobalt '05" },
    { "RANCHERX", "Chevrolet Suburban '73" },
    { "RHAPSODY", "AMC Pacer '75" },
    { "SABREGT", "Chevrolet Chevelle '70" },
    { "SABREGT2", "Chevrolet Chevelle (Custom)" },
    { "SCRAMJET", "Mach 5 '60" },
    { "STALION", "Ford Mustang '67" },
    { "STALION2", "Oldsmobile Cutlass (Burger Shot)" },
    { "TAHOMA", "Chevrolet Monte Carlo '78" },
    { "TAMPA", "Dodge Dart Demon '70" },
    { "TAMPA2", "Ford Mustang Hoonicorn RTR '65" },
    { "TAMPA3", "Dodge Dart Demon (Weaponized)" },
    { "TAMPA4", "Plymouth Belvedere GTX '67" },
    { "TORNADO", "Chevrolet Bel Air '57" },
    { "TORNADO2", "Chevrolet Bel Air '57" },
    { "TORNADO3", "Chevrolet Bel Air '57" },
    { "TORNADO5", "Chevrolet Bel Air '57 (Custom)" },
    { "TORNADO6", "Chevrolet Bel Air '57 (Rat Rod)" },
    { "TULIP", "Chevrolet Chevelle Malibu '72" },
    { "TULIP2", "Chevrolet Malibu Coupe '78" },
    { "VAMOS", "Chevrolet Nova '68" },
    { "VIGERO", "Chevrolet Camaro '67" },
    { "VIGERO2", "Chevrolet Camaro ZL1 '17" },
    { "VIGERO3", "Chevrolet Camaro ZL1 Convertible '17" },
    { "VOODOO", "Chevrolet Impala '60" },
    { "VOODOO2", "Chevrolet Impala '60 (Custom)" },
    { "YOSEMITE", "Chevrolet C10 '67" },
    { "YOSEMITE2", "Ken Blockâs Ford F-150 '77 'Hoonitruck'" },
    { "YOSEMITE3", "Chevrolet K10 '67" },
    { "YOSEMITE4", "Chevrolet Silverado (GMT800) '99" },

    -- Dewbauchee / Aston Martin
    { "CHAMPION", "Aston Martin Victor '20" },
    { "EXEMPLAR", "Aston Martin Rapide '10" },
    { "JB700", "Aston Martin DB5 '63" },
    { "JB7002", "Aston Martin DB5 '63 (Weaponized)" },
    { "MASSACRO", "Aston Martin Vanquish '12" },
    { "MASSACRO2", "Aston Martin Vanquish '12 (Race)" },
    { "RAPIDGT", "Aston Martin V8 Vantage '05" },
    { "RAPIDGT3", "Aston Martin V8 Vantage '77" },
    { "RAPIDGT4", "Aston Martin Vantage '25" },
    { "SEVEN70", "Aston Martin One-77 '09" },
    { "SPECTER", "Aston Martin DB10 '14" },
    { "SPECTER2", "Aston Martin DB10 '14 (Custom)" },
    { "VAGNER", "Aston Martin Valkyrie '18" },

    -- Dinka / Honda, Toyota
    { "AKUMA", "Buell XB12S" },
    { "BLISTA", "Honda Civic Type R FN2" },
    { "BLISTA2", "Honda CR-X '88" },
    { "BLISTA3", "Honda CR-X '88 (Monkey)" },
    { "CHAVOSV6", "Honda Accord (9th gen) '13" },
    { "DOUBLE", "Honda CBR1000RR '08" },
    { "DRIFTCHAVOSV6", "Honda Accord (Drift)" },
    { "DRIFTJESTER", "Toyota GR Supra (A90) (Drift)" },
    { "DRIFTJSTR3", "Toyota Supra (A80) (Drift)" },
    { "DRIFTRT3000", "Honda S2000 (Drift)" },
    { "ENDURO", "Honda CB250" },
    { "JESTER", "Honda NSX (NA1) '91" },
    { "JESTER2", "Honda NSX (NA1) (Race)" },
    { "JESTER3", "Toyota Supra (A80) '94" },
    { "JESTER4", "Toyota GR Supra (A90) '20" },
    { "JESTER5", "Toyota GR Supra (A90) Widebody" },
    { "KANJO", "Honda Civic Type R EK9" },
    { "KANJOSJ", "Honda Civic EJ '92" },
    { "MARQUIS", "Adjutor Yacht" },
    { "POSTLUDE", "Honda Prelude (SN) '78" },
    { "RT3000", "Honda S2000 '99" },
    { "SUGOI", "Honda Civic Type R FK8 '17" },
    { "THRUST", "Honda DN-01" },
    { "VERUS", "Arctic Cat Alterra 570" },
    { "VETO", "Rupp Dart A-Bone Kart '65" },
    { "VETO2", "Rupp Dart A-Bone Kart (Modern)" },
    { "VINDICATOR", "Honda NM4" },

    -- Dundreary / Lincoln, Mercury
    { "LANDSTAL", "Lincoln Navigator '07" },
    { "LANDSTLKR2", "Lincoln Navigator L '18" },
    { "REGINA", "Plymouth Fury Sport Suburban '73" },
    { "STRETCH", "Lincoln Town Car Limo '98" },
    { "VIRGO2", "Mercury Cougar '77" },
    { "VIRGO3", "Mercury Cougar '77 (Custom)" },

    -- Emperor / Cadillac DeVille (label shared with Lexus make)
    { "EMPEROR", "Cadillac DeVille '77" },
    { "HABANERO", "Lexus RX (XU30) '03" },
    { "SHEAVA", "Lexus LFA '10" },
    { "VECTRE", "Lexus RC F (USC10) '19" },

    -- Enus / Bentley, Rolls-Royce
    { "COG55", "Bentley Flying Spur LWB '09" },
    { "COG552", "Bentley Flying Spur LWB (Armored)" },
    { "COGCABRI", "Bentley Continental GTC '06" },
    { "COGNOSC", "Bentley Flying Spur '09" },
    { "COGNOSC2", "Bentley Flying Spur (Armored)" },
    { "DEITY", "Bentley Flying Spur '19" },
    { "HUNTLEY", "Bentley EXP 9 F" },
    { "JUBILEE", "Rolls-Royce Cullinan" },
    { "PARAGON", "Bentley Continental GT '18" },
    { "PARAGON2", "Bentley Continental GT (Armored)" },
    { "PARAGON3", "Bentley Mulliner Batur '22" },
    { "STAFFORD", "Rolls-Royce Silver Cloud '55" },
    { "SUPERD", "Rolls-Royce Phantom VII" },
    { "WINDSOR", "Rolls-Royce Wraith '14" },
    { "WINDSOR2", "Rolls-Royce Dawn '15" },

    -- Fathom / Infiniti
    { "DRIFTFR36", "Infiniti G35 (V35) (Drift)" },
    { "FQ2", "Infiniti QX70 (S51)" },
    { "FR36", "Infiniti G35 (V35)" },

    -- Gallivanter / Land Rover
    { "BALLER", "Range Rover L322 '02" },
    { "BALLER2", "Range Rover Sport '13" },
    { "BALLER3", "Range Rover SVR '15" },
    { "BALLER4", "Range Rover SVR LWB '15" },
    { "BALLER5", "Range Rover SVR '15 (Armored)" },
    { "BALLER6", "Range Rover SVR LWB (Armored)" },
    { "BALLER7", "Range Rover Sport SVR (L494) '18" },
    { "BALLER8", "Range Rover L460" },

    -- Grotti / Ferrari, Fiat
    { "BESTIAGTS", "Ferrari FF '11" },
    { "BRIOSO", "Fiat 500 '07" },
    { "BRIOSO2", "Fiat 500 '70" },
    { "BRIOSO3", "Fiat 500 '70 Widebody" },
    { "CARBONIZ", "Ferrari F12" },
    { "CHEETAH", "Ferrari Enzo" },
    { "CHEETAH2", "Ferrari Testarossa" },
    { "CHEETAH3", "Ferrari Testarossa (LSCM)" },
    { "FURIA", "Pininfarina Battista (PF0)" },
    { "GT500", "Ferrari 250 GT Berlinetta" },
    { "GT750", "Ferrari 365 GTB/4 Daytona" },
    { "ITALI2", "Ferrari 308 GTS" },
    { "ITALIGTO", "Ferrari 812 Superfast" },
    { "ITALIRSX", "Ferrari SF90 Stradale" },
    { "PROTOTIPO", "Ferrari F80" },
    { "STINGER", "Ferrari 250 GT California Spyder" },
    { "STINGERG", "Ferrari 250 GTO" },
    { "STINGERTT", "Ferrari Roma" },
    { "TURISMO2", "Ferrari F40" },
    { "TURISMO3", "Ferrari 12Cilindri" },
    { "TURISMOR", "Ferrari LaFerrari" },
    { "VISIONE", "Ferrari Xezri Concept" },

    -- Hijak / Fisker
    { "KHAMEL", "Fisker Karma '11" },
    { "RUSTON", "VUHL 05 '08" },

    -- HVY / heavy vehicles
    { "APC", "BRDM-2" },
    { "BARRACKS2", "Freightliner M915A5" },
    { "BIFF", "Kenworth T800" },
    { "BULLDOZE", "Caterpillar 963D" },
    { "CUTTER", "Bucket-Wheel Excavator" },
    { "DUMP", "Caterpillar 789" },
    { "FORK", "LXE40 Spark Lithium Forklift Truck" },
    { "INSURGENT", "Terradyne GURKHA RPV" },
    { "INSURGENT2", "Terradyne GURKHA LAPV" },
    { "INSURGENT3", "Terradyne GURKHA RPV (Custom)" },
    { "MENACER", "Boss Hunting Truck" },
    { "MIXER", "Mack DM Cement Mixer" },
    { "MIXER2", "Mack DM Cement Mixer" },
    { "NIGHTSHARK", "Dartz" },
    { "SCARAB", "Howe & Howe Ripsaw EV2 (Apocalypse)" },
    { "SCARAB2", "Howe & Howe Ripsaw EV2 (Future Shock)" },
    { "SCARAB3", "Howe & Howe Ripsaw EV2 (Nightmare)" },

    -- Imponte / Pontiac, Dodge
    { "ARBITERGT", "Chevrolet Chevelle Wagon '70" },
    { "DELUXO", "DeLorean DMC-12 '81" },
    { "DUKES", "Dodge Charger '68" },
    { "DUKES2", "Dodge Charger (Armored)" },
    { "DUKES3", "Dodge Charger (Beater)" },
    { "NITESHAD", "Pontiac GTO '68" },
    { "PHOENIX", "Pontiac Firebird '70" },
    { "RUINER", "Pontiac Firebird '82" },
    { "RUINER2", "Pontiac Firebird K.I.T.T." },
    { "RUINER4", "Pontiac Firebird '98" },

    -- Invetero / Chevrolet Corvette
    { "COQUETTE", "Chevrolet Corvette C7 '14" },
    { "COQUETTE2", "Chevrolet Corvette C2 '63" },
    { "COQUETTE3", "Chevrolet Corvette C1 '61" },
    { "COQUETTE4", "Chevrolet Corvette C8 '20" },
    { "COQUETTE5", "Chevrolet Corvette C1 '56" },
    { "COQUETTE6", "Chevrolet Corvette C6 '05" },
    { "POLCOQUTT4", "Chevrolet Corvette C8 (Police)" },

    -- JoBuilt / Peterbilt
    { "HAULER", "Peterbilt 362" },
    { "HAULER2", "Peterbilt 362 Pacemaker Goliath" },
    { "PHANTOM", "Peterbilt 359 EXHD" },
    { "PHANTOM2", "Peterbilt 359 EXHD 'Wedge Truck'" },
    { "PHANTOM3", "GMC General '84" },
    { "RUBBLE", "Peterbilt 359 EXHD 'Dump truck'" },

    -- Karin / Toyota, Mitsubishi, Subaru
    { "ASTEROPE2", "Toyota Camry (XV30) '01" },
    { "ASTROPE", "Toyota Camry (XV40) '06" },
    { "BJXL", "Toyota FJ Cruiser (XJ10) '06" },
    { "BOOR", "Subaru BRAT '81" },
    { "CALICO", "Toyota Celica GT-Four ST205 '94" },
    { "DILETTAN", "Toyota Prius (XW20) '03" },
    { "DRIFTFUTO", "Toyota AE86 Sprinter Trueno (Drift)" },
    { "DRIFTFUTO2", "Toyota AE86 Corolla Levin (Drift)" },
    { "EVERON", "Toyota Hilux Arctic Trucks AT37 '18" },
    { "EVERON2", "Toyota Tundra TRD Pro NASCAR '22" },
    { "EVERON3", "Toyota Tacoma X-Runner" },
    { "FUTO", "Toyota AE86 Corolla Levin '83" },
    { "FUTO2", "Toyota AE86 Sprinter Trueno '83" },
    { "INTRUDER", "Infiniti Q45 (F50) '01" },
    { "KURUMA", "Mitsubishi Lancer Evolution X '07" },
    { "KURUMA2", "Mitsubishi Lancer Evolution X (Armored)" },
    { "PREVION", "Toyota Soarer (Z30) '91" },
    { "REBEL01", "Toyota Hilux '83 (Rusty)" },
    { "REBEL02", "Toyota Hilux '83" },
    { "S95", "Toyota Scion FR-S (ZN6/ZC6) '12" },
    { "SULTAN", "Mitsubishi Lancer Evolution IX" },
    { "SULTAN2", "Mitsubishi Lancer Evo I" },
    { "SULTAN3", "Mitsubishi Lancer Evo III" },
    { "SULTANRS", "Toyota Altezza RS (XE10) '98" },
    { "TECHNICAL", "Toyota Hilux '83 (Armed)" },
    { "TECHNICAL2", "Toyota Hilux '83 (Armed)" },
    { "TECHNICAL3", "Toyota Hilux '83 (Armed)" },
    { "VIVANITE", "Toyota Sienna (XL40) '20" },
    { "VIVANITE2", "Toyota Sienna (KnoWay)" },
    { "WOODLANDER", "Subaru Forester STI" },
    { "Z190", "Nissan Fairlady Z (S30) '69" },

    -- Kraken / subs
    { "AVISA", "SEAmagine AURORA-6" },

    -- Lampadati / Maserati, Alfa Romeo
    { "CASCO", "Maserati 3500 GT" },
    { "CINQUEMILA", "Maserati Quattroporte 6" },
    { "CORSITA", "Maserati MC20" },
    { "FELON", "Maserati Quattroporte 5" },
    { "FELON2", "Maserati GranCabrio" },
    { "FURORE", "Maserati GranTurismo" },
    { "MICHELLI", "Alfa Romeo Giulia Sprint GTV '60" },
    { "PIGALLE", "Maserati Merak" },
    { "TORO", "Riva Aquarama" },
    { "TROPOS", "Lancia Stratos" },

    -- Lampadati (alt label)
    { "KOMODA", "Alfa Romeo Giulia Quadrifoglio (952)" },
    { "NOVAK", "Maserati Levante (Tipo M161)" },
    { "TIGON", "De Tomaso P72" },
    { "VISERIS", "De Tomaso Pantera" },

    -- LCC / Harley-style
    { "AVARUS", "Harley-Davidson Dyna" },
    { "HEXER", "Harley-Davidson Softail" },
    { "INNOVATION", "Harley-Davidson Rocker" },
    { "SANCTUS", "Western Sanctus Chopper" },

    -- Maibatsu / Mitsubishi
    { "MANCHEZ", "FX Bikes Mountain Moto FX5" },
    { "MANCHEZ2", "Armstrong MT500" },
    { "MANCHEZ3", "Armstrong MT500" },
    { "MONSTROCITI", "Mitsubishi Pajero Evolution '97" },
    { "MULE", "Isuzu Elf" },
    { "MULE4", "Isuzu Elf (Custom)" },
    { "MULE5", "Isuzu Elf '94" },
    { "PENUMBRA", "Mitsubishi Eclipse '06" },
    { "PENUMBRA2", "Mitsubishi Eclipse '95" },
    { "SANCHEZ01", "Yamaha YZ450F" },
    { "SANCHEZ02", "Yamaha YZ450F" },

    -- Mammoth / Hummer, aircraft
    { "AVENGER", "Boeing V-22 Osprey" },
    { "AVENGER3", "Boeing V-22 Osprey" },
    { "DODO", "Grumman G-21 Goose" },
    { "HYDRA", "AV-8B Harrier II" },
    { "MOGUL", "Beechcraft Model 18" },
    { "PATRIOT", "Hummer H2 '03" },
    { "PATRIOT2", "Hummer H2 Limousine '03" },
    { "PATRIOT3", "Hummer H1 Mil-Spec" },
    { "SQUADDIE", "Hummer H1" },
    { "STREAMER216", "De Havilland Canada DHC-6 Twin Otter" },
    { "THRUSTER", "Martin Jetpack P12" },
    { "TULA", "Kaman K-16B" },

    -- Maxwell / Vauxhall, Ariel
    { "ASBO", "Vauxhall Corsa D" },
    { "VAGRANT", "Ariel Nomad" },

    -- MTL / Mack, MAN
    { "BRICKADE", "MAN TGS 26.480 6x6 Expedition Truck" },
    { "BRICKADE2", "MAN TGS 26.480 6x6 Expedition Truck" },
    { "CERBERUS", "War Rig (Apocalypse)" },
    { "CERBERUS2", "War Rig (Future Shock)" },
    { "CERBERUS3", "War Rig (Nightmare)" },
    { "FIRETRUK", "Seagrave Fire Truck" },
    { "FLATBED", "Mack CH613" },
    { "FLATBED2", "Freightliner Century Class" },
    { "PACKER", "Mack CH613" },
    { "POUNDER", "Mack CH613" },
    { "POUNDER2", "Mack CH613" },
    { "RALLYTRUCK", "Dakar MAN TGS 480" },
    { "WASTLNDR", "Heist Truck concept 'Mongo'" },

    -- Nagasaki / Kawasaki, ATVs
    { "BF400", "KTM 450 Rally" },
    { "BLAZER", "Yamaha YFZ450R" },
    { "BLAZER03", "Yamaha YFZ450R Hot Rod" },
    { "BLAZER2", "Honda Fourtrax 250" },
    { "BLAZER4", "Yamaha YFZ450R Sport" },
    { "BLAZER5", "Gibbs Quadski" },
    { "CARBON", "Ducati 1199" },
    { "CHIMERA", "Chimera" },
    { "DINGHY", "Zodiac Hurricane CZ7" },
    { "DINGHY5", "Zodiac Hurricane CZ7 (Weaponized)" },
    { "HAVOK", "Heli-Sport CH-7" },
    { "MICROLIGHT", "Air Creation Racer" },
    { "OUTLAW", "Can-Am Maverick X3" },
    { "SHINOBI", "Kawasaki Ninja 250R" },
    { "SHOTARO", "Light Cycle 'Tron'" },
    { "STRYDER", "Lazareth Triazuma" },

    -- Obey / Audi
    { "DRAFTER", "Audi RS5 Coupe (8W6)" },
    { "IWAGEN", "Audi Q8 e-tron" },
    { "NINEF", "Audi R8 (Type 42)" },
    { "NINEF2", "Audi R8 V10 Spyder" },
    { "OMNIS", "Audi Sport Quattro S1" },
    { "OMNISEGT", "Audi e-tron GT" },
    { "ROCOTO", "Audi Q5 (8R)" },
    { "TAILGATE", "Audi A6 (C6)" },
    { "TAILGATER2", "Audi RS3 Saloon (8V)" },
    { "TENF", "Audi R8 (Type 4S)" },
    { "TENF2", "Audi R8 (Widebody)" },

    -- Ocelot / Jaguar, Lotus
    { "ARDENT", "Lotus Esprit '93" },
    { "F620", "Jaguar XK '06" },
    { "FORMULA2", "Lotus 97T" },
    { "JACKAL", "Jaguar XF '07" },
    { "JUGULAR", "Jaguar XE SV Project 8 '18" },
    { "LOCUST", "Lotus 3-Eleven '16" },
    { "LYNX", "Jaguar F-Type '13" },
    { "PARIAH", "Aston Martin Vanquish Zagato" },
    { "PENETRATOR", "Jaguar XJ220 '92" },
    { "STROMBERG", "Lotus Esprit S1 'Wet Nellie' '76" },
    { "SWINGER", "Jaguar XJ13 '66" },
    { "VIRTUE", "Lotus Evija" },
    { "XA21", "Jaguar C-X75 '10" },

    -- Overflod / Koenigsegg
    { "AUTARCH", "Scuderia Cameron Glickenhaus SCG 003" },
    { "ENTITY2", "Koenigsegg One:1 '15" },
    { "ENTITY3", "Koenigsegg Jesko '21" },
    { "ENTITYXF", "Koenigsegg CCX '06" },
    { "IMORGON", "Roland Gumpert Nathalie" },
    { "PIPISTRELLO", "Estrema Fulminea '23" },
    { "SUZUME", "Aspark Owl" },
    { "TYRANT", "Apollo Arrow '16" },
    { "ZENO", "SSC Tuatara '20" },

    -- Pegassi / Lamborghini, Pagani, Ducati
    { "BATI", "Ducati 1098" },
    { "BATI2", "Ducati 1098 R" },
    { "ESSKEY", "Ducati Scrambler" },
    { "FAGGIO", "Piaggio Vespa" },
    { "FAGGIO3", "Piaggio Vespa (Custom)" },
    { "FAGGION", "Piaggio Zip" },
    { "FCR", "BMW K100" },
    { "FCR2", "BMW K100 (Custom)" },
    { "IGNUS", "Lamborghini Sian FKP 37" },
    { "IGNUS2", "Lamborghini Sian (Weaponized)" },
    { "INFERNUS", "Lamborghini Murcielago" },
    { "INFERNUS2", "Lamborghini Diablo" },
    { "MONROE", "Lamborghini Miura" },
    { "OPPRESSOR", "Honda XR 500" },
    { "OPPRESSOR2", "BMW R1200GS Hover Bike Concept" },
    { "OSIRIS", "Pagani Huayra" },
    { "PIZZABOY", "Peugeot V Clic '10" },
    { "REAPER", "W Motors Lykan HyperSport" },
    { "RUFFIAN", "Ducati Monster 1100 Evo" },
    { "SPEEDER", "Riva Aquarama '62" },
    { "TEMPESTA", "Lamborghini Huracan" },
    { "TEZERACT", "Lamborghini Terzo Millennio '17" },
    { "TOREADOR", "Lamborghini Marzal" },
    { "TORERO", "Lamborghini Countach '74" },
    { "TORERO2", "Lamborghini Countach LPI 800-4" },
    { "TOROS", "Lamborghini Urus" },
    { "VACCA", "Lamborghini Gallardo '08" },
    { "VORTEX", "Ducati 1199 Panigale" },
    { "ZENTORNO", "Lamborghini Sesto Elemento '12" },
    { "ZORRUSSO", "Italdesign Zerouno '17" },

    -- Penaud / Renault
    { "COUREUR", "Renault R5 Turbo 3E '22" },

    -- Pfister / Porsche
    { "ASTRALE", "Porsche 928 Restomod" },
    { "ASTRON", "Porsche Macan (95B)" },
    { "ASTRON2", "Porsche Macan (Custom)" },
    { "COMET2", "Porsche 997 GT2" },
    { "COMET3", "Porsche 911 Turbo (964)" },
    { "COMET4", "Porsche 911 Safari" },
    { "COMET5", "Porsche 997 GT2 RS" },
    { "COMET6", "Porsche 911 (992)" },
    { "COMET7", "Porsche 911 (992) Cabriolet" },
    { "GROWLER", "Porsche 718 Cayman" },
    { "NEON", "Porsche Taycan" },
    { "PFISTER811", "Porsche 918 Spyder" },
    { "XTREME", "Porsche Mission X" },

    -- Principe / Ducati
    { "DEVESTE", "Devel Sixteen '18" },
    { "DIABLOUS", "Ducati Streetfighter 848 '15" },
    { "DIABLOUS2", "Ducati Streetfighter 848 (Custom)" },
    { "LECTRO", "Ducati Streetfighter S" },
    { "NEMESIS", "Ducati Monster" },

    -- Progen / McLaren
    { "EMERUS", "McLaren Senna GTR" },
    { "FORMULA", "McLaren MP4/6" },
    { "GP1", "McLaren F1" },
    { "ITALIGTB", "McLaren 570S" },
    { "ITALIGTB2", "McLaren 570S GT4/Sprint" },
    { "LUIVA", "McLaren Elva" },
    { "T20", "McLaren P1" },
    { "TYRUS", "McLaren F1 GTR" },

    -- RUNE / Lada
    { "CHEBUREK", "VAZ 2106" },
    { "DRIFTCHEBU", "VAZ 2106 (Drift)" },
    { "KOSATKA", "Delta III-class submarine" },
    { "ZHABA", "SHERP ATV" },

    -- Schyster / Chrysler, AMC
    { "DEVIANT", "AMC Javelin '70" },
    { "FUSILADE", "Chrysler Crossfire '04" },

    -- Shitzu / Suzuki
    { "DEFILER", "Suzuki Bandit 1200" },
    { "DRIFTKEITORA", "Suzuki Carry (Drift)" },
    { "HAKUCHOU", "Suzuki GSX-R 1300 Hayabusa" },
    { "HAKUCHOU2", "Suzuki GSX-R 1300 Hayabusa (Drag)" },
    { "JETMAX", "Fountain 32 Fever" },
    { "KEITORA", "Suzuki Carry" },
    { "LONGFIN", "Magnum Marine 44' Banzai" },
    { "PCJ", "Honda CB600F" },
    { "SQUALO", "Fibrafort 265" },
    { "SUNTRAP", "Bryant 219" },
    { "TROPIC", "Sea Ray 300 Sundancer" },
    { "VADER", "Kawasaki Z1000" },

    -- Speedophile / boats
    { "SEASHARK", "Sea-Doo RXT-X 260" },

    -- Stanley
    { "TRACTOR2", "John Deere 7310R" },

    -- Toundra / Alpine
    { "PANTHERE", "Alpine A110 '17" },

    -- Truffade / Bugatti
    { "ADDER", "Bugatti Veyron Super Sport '10" },
    { "NERO", "Bugatti Chiron" },
    { "NERO2", "Bugatti Vision Gran Turismo" },
    { "THRAX", "Bugatti Divo" },
    { "ZTYPE", "Bugatti Type 57SC Atlantic '38" },

    -- Ubermacht / BMW
    { "DRIFTSENT", "BMW E30 M3 '86" },
    { "DRIFTSENTINEL2", "BMW 3 Series (E93) (Drift)" },
    { "ORACLE", "BMW 7 Series (E65)" },
    { "ORACLE2", "BMW 7 Series (E65) XS" },
    { "REVOLTER", "Cadillac Escala Concept" },
    { "SC1", "BMW M1 Homage Concept" },
    { "SENTINEL", "BMW 3 Series (E92)" },
    { "SENTINEL2", "BMW 3 Series (E93)" },
    { "SENTINEL3", "BMW M3 E30" },
    { "SENTINEL4", "BMW M3 E30 LTO" },
    { "ZION", "BMW 650i E63 Coupe" },
    { "ZION2", "BMW 650i E63 Cabrio" },
    { "ZION3", "BMW M635CSi (E24)" },

    -- Ubermacht (alt label)
    { "CYPHER", "BMW M2 F87" },
    { "DRIFTCYPHER", "BMW M2 F87 '15" },
    { "NIOBE", "BMW i8 '13" },
    { "REBLA", "BMW X5 (G05)" },
    { "RHINEHART", "BMW 3 Series Touring (G21)" },
    { "SENTINEL5", "BMW M3 (G80)" },
    { "SENTINEL6", "BMW M5 (E39)" },

    -- Vapid / Ford
    { "ALEUTIAN", "Ford Expedition '18 (U553)" },
    { "BENSON", "International 4000 series '89" },
    { "BENSON2", "International 4000 series '89 (Cluckin' Bell)" },
    { "BLADE", "Ford Falcon '64" },
    { "BOBCATXL", "Ford F-150 '73" },
    { "BULLET", "Ford GT '05" },
    { "CARACARA", "Hennessey Velociraptor 6x6" },
    { "CARACARA2", "Ford F-150 '15" },
    { "CHINO", "Lincoln Continental '64" },
    { "CHINO2", "Lincoln Continental (Custom)" },
    { "CLIQUE", "Ford Shoebox '51" },
    { "CLIQUE2", "Ford Country Squire '51" },
    { "CONTENDER", "Ford F-150 SuperCrew" },
    { "DOMINATO", "Ford Mustang GT '05" },
    { "DOMINATO2", "Ford Mustang GT (Pisswasser)" },
    { "DOMINATOR10", "Ford Mustang '79" },
    { "DOMINATOR3", "Ford Mustang GT (S550) '15" },
    { "DOMINATOR4", "Ford Mustang Shelby GT500 '05" },
    { "DOMINATOR5", "Ford Mustang Shelby GT500 '05" },
    { "DOMINATOR6", "Ford Mustang Shelby GT500 '05" },
    { "DOMINATOR7", "Ford Mustang SVT Cobra R" },
    { "DOMINATOR8", "Ford Mustang Boss 302 '69" },
    { "DOMINATOR9", "Ford Mustang Convertible '18" },
    { "DRIFTDOMINATOR10", "Ford Mustang '79 (Drift)" },
    { "DRIFTDOMINATOR9", "Ford Mustang (S550) (Drift)" },
    { "ELLIE", "Shelby Mustang GT500 '67" },
    { "FIREBOLT", "Ford F-150 SVT Lightning '01" },
    { "FLASHGT", "Ford Focus RS RX (WRX)" },
    { "FMJ", "Ford GT '17" },
    { "FMJ2", "Ford GT Mk IV" },
    { "GB200", "Ford RS200" },
    { "GUARDIAN", "Ford F-650 Truck" },
    { "HOTKNIFE", "Ford Model A '20" },
    { "HUSTLER", "Ford Coupe '33" },
    { "IMPERATOR", "Ford Falcon XB GT '73 (Apocalypse)" },
    { "IMPERATOR2", "Ford Falcon XB GT '73 (Future Shock)" },
    { "IMPERATOR3", "Ford Falcon XB GT '73 (Nightmare)" },
    { "MINIVAN", "Ford Windstar '99" },
    { "MINIVAN2", "Ford Windstar (Custom)" },
    { "MONSTER", "Ford F-250 Monster Truck" },
    { "PEYOTE", "Ford Thunderbird '55" },
    { "PEYOTE2", "Ford Thunderbird 'Bird of Prey' Gasser '55" },
    { "PEYOTE3", "Ford Thunderbird '55" },
    { "POLCARACAR", "Ford F-150 (Police)" },
    { "POLDOM10", "Ford Mustang '79 (Police)" },
    { "POLICE4", "Ford Crown Victoria Unmarked '92" },
    { "POLICE5", "Ford Crown Victoria Police Interceptor '92" },
    { "RADI", "Ford Edge (U387)" },
    { "RATEL", "Brenthel Industries Class 1 Buggy" },
    { "RETINUE", "Ford Escort MK 1" },
    { "RETINUE2", "Ford Escort MK 2" },
    { "RIATA", "Ford Bronco Concept '17" },
    { "SADLER", "Ford F-250 Super Duty '99" },
    { "SANDKIN2", "Ford F-350 Super Duty '11" },
    { "SANDKING", "Ford Super Duty '11" },
    { "SLAMTRUCK", "Suzy Stuchel's Ford COE 600 Hauler '56" },
    { "SLAMVAN", "Ford F-Series '53" },
    { "SLAMVAN2", "Ford F-Series Panel Van '53" },
    { "SLAMVAN3", "Ford F-Series '53" },
    { "SLAMVAN4", "Ford F6 '50 'Stubby Bob' (Apocalypse)" },
    { "SLAMVAN5", "Ford F6 '50 'Stubby Bob' (Future Shock)" },
    { "SLAMVAN6", "Ford F6 '50 'Stubby Bob' (Nightmare)" },
    { "SPEEDO", "Chevrolet Express '03" },
    { "SPEEDO2", "Chevrolet Express (Clown)" },
    { "SPEEDO4", "Chevrolet Express (Custom)" },
    { "STANIER", "Ford Crown Victoria '98" },
    { "TROPHY", "Ford F-150 Baja" },
    { "TROPHY2", "Red Bull SMG Buggy" },
    { "URANUS", "Ford Sierra RS Cosworth '86" },
    { "WINKY", "Ford GPW" },
    { "YOUGA4", "Ford Econoline (Custom)" },

    -- Vulcar / Volvo, Datsun
    { "DRIFTNEBULA", "Volvo 242 '74" },
    { "FAGALOA", "Volvo Amazon Station Wagon" },
    { "INGOT", "Volvo V70 (R)" },
    { "NEBULA", "Volvo 242 Coupe" },
    { "WARRENER", "Datsun 510" },
    { "WARRENER2", "Datsun Sunny Hakotora Pickup" },

    -- Vysser / Spyker
    { "NEO", "Spyker C8 Aileron" },

    -- Weeny / MINI
    { "DYNASTY", "Hindustan Ambassador '58" },
    { "ISSI2", "Mini Cooper R50 '01" },
    { "ISSI3", "Mini MK II '67" },
    { "ISSI4", "Mini Cooper S 'The Mini' (Apocalypse)" },
    { "ISSI5", "Mini Cooper S 'The Mini' (Future Shock)" },
    { "ISSI6", "Mini Cooper S 'The Mini' (Nightmare)" },
    { "ISSI7", "Mini Hatch '18" },
    { "ISSI8", "Mini John Cooper Works WRC" },

    -- Western / Harley-Davidson
    { "BAGGER", "Harley Davidson Touring Road Glide Custom '13" },
    { "BESRA", "Aero L-39 Albatros" },
    { "CLIFFHANGER", "Harley-Davidson XR-750" },
    { "DAEMON", "Harley-Davidson Dyna Street Bob" },
    { "DAEMON2", "Harley-Davidson Dyna Street Bob (Custom)" },
    { "DEATHBIKE", "Harley-Davidson Dyna (Walking Dead)" },
    { "DEATHBIKE2", "Indian Scout Bobber (Future Shock)" },
    { "DEATHBIKE3", "Indian Scout Bobber (Nightmare)" },
    { "DUSTER2", "Air Tractor AT-802" },
    { "GARGOYLE", "Indian 101 Scout '28" },
    { "NIGHTBLADE", "Harley-Davidson Night Rod Special" },
    { "POLICEB2", "Harley-Davidson Road King (Police)" },
    { "POWERSURGE", "Harley-Davidson LiveWire '19" },
    { "RATBIKE", "Harley-Davidson 1200" },
    { "REEVER", "ARCH Method 143" },
    { "ROGUE", "Beechcraft T-6 Texan II" },
    { "RROCKET", "Rocket II Trike" },
    { "SEABREEZE", "Seawind 3000" },
    { "SOVEREIGN", "Harley-Davidson Road King" },
    { "WOLFSBANE", "Harley-Davidson 1200" },
    { "ZOMBIEA", "Exile Hot Rod" },
    { "ZOMBIEB", "Exile Hot Rod" },

    -- Willard / Buick
    { "EUDORA", "Buick Electra '59" },
    { "FACTION", "Buick Regal '82" },
    { "FACTION2", "Buick Regal (Custom)" },
    { "FACTION3", "Buick Regal (Custom Donk)" },
    { "POLFCTION2", "Buick Regal (Police)" },

    -- Zirconium / Saturn, Honda
    { "JOURNEY", "Triple E '77" },
    { "JOURNEY2", "Triple E '77" },
    { "STRATUM", "Honda Accord Wagon '94" },

    -- Other / shared / later DLC
    { "AIRBUS", "Airport Apron Bus" },
    { "AIRTUG", "Clark CT 30" },
    { "AKULA", "Boeing-Sikorsky RAH-66 Comanche" },
    { "ALKONOST", "Beriev A-40 Albatros" },
    { "AMBULAN", "GMC 3500 Cab (Ambulance)" },
    { "ANNIHL", "Sikorsky UH-60 Black Hawk" },
    { "ANNIHLATOR2", "Sikorsky UH-60 Black Hawk (Stealth)" },
    { "BARRACKS", "Oshkosh MTVR" },
    { "BARRAGE", "HDT Storm SRTV" },
    { "BLIMP", "Atomic Blimp" },
    { "BLIMP2", "Xero Blimp" },
    { "BLIMP3", "Blimp" },
    { "BMX", "BMX Bike" },
    { "BOMBUSHKA", "Antonov An-12" },
    { "BOXVILLE5", "GMC Stepvan (Armored)" },
    { "BUS", "New Flyer D901" },
    { "BUZZARD", "AH-6 Little Bird" },
    { "BUZZARD2", "MH-6 Little Bird" },
    { "CABLECAR", "San Francisco Cable Car" },
    { "CADDY", "Golf Cart" },
    { "CADDY3", "Caddy (Armed)" },
    { "CARGOBOB", "Sikorsky MH-53 Pave Low" },
    { "CARGOPL", "Antonov An-124 Ruslan" },
    { "CHERNOBOG", "MAZ-543M" },
    { "COACH", "MCI 102DL3 Dashound" },
    { "CRUISER", "Cruiser Bicycle" },
    { "CUBAN800", "Piper PA-30 Twin Comanche" },
    { "DOCKTUG", "Ottawa Commando 4x2" },
    { "DUNE2", "Space Docker" },
    { "DUNE4", "Ramp Buggy" },
    { "DUNE5", "Ramp Buggy" },
    { "DUSTER", "Stearman PT-17" },
    { "FBI", "Dodge Charger Pursuit '06" },
    { "FBI2", "Chevrolet Suburban (FIB)" },
    { "FIXTER", "Fixter Bicycle" },
    { "FROGGER", "Eurocopter EC130" },
    { "HANDLER", "Taylor TEC950L" },
    { "HUNTER", "Boeing AH-64 Apache" },
    { "INDUCTOR", "Delfast Top 3.0i" },
    { "INDUCTOR2", "Delfast Top 3.0i (Junk Energy)" },
    { "JET", "Boeing 747-400" },
    { "KHANJALI", "Polish PL-01" },
    { "LAZER", "F-16 Fighting Falcon" },
    { "MAMMATUS", "Cessna 172 Skyhawk" },
    { "MAVERICK", "Bell 206" },
    { "MAVERICK2", "Bell 206L LongRanger" },
    { "MINITANK", "Invade and Persuade Tank" },
    { "MOLOTOK", "Mikoyan-Gurevich MiG-15" },
    { "MOWER", "John Deere LX172" },
    { "NOKOTA", "North American P-51 Mustang" },
    { "PATROLBOAT", "Preserved PBR 829" },
    { "PBUS", "Blue Bird CV200" },
    { "PBUS2", "Festival Bus" },
    { "POLICE", "Ford Taurus Police Interceptor '13" },
    { "POLICE2", "Dodge Charger Pursuit '06" },
    { "POLICEB", "Harley-Davidson Road King FLHP (Police)" },
    { "POLICEO1", "Chevrolet Suburban '73 (Police)" },
    { "POLICEO2", "Cadillac Seville (Police)" },
    { "POLICET", "Chevrolet Express Van '96 (Police)" },
    { "POLICET3", "Chevrolet Express Van '96" },
    { "POLMAV", "Eurocopter AS350" },
    { "PREDATOR", "Type PP-601" },
    { "RAIJU", "Lockheed Martin F-35 Lightning II" },
    { "RCBANDITO", "RC Bandito" },
    { "RENTBUS", "Ford E-Series Shuttle" },
    { "RHINO", "Leopard 2A4" },
    { "RIOT", "Lenco BearCat" },
    { "RIOT2", "INKAS Armored Riot Control Vehicle" },
    { "RIPLEY", "Schopf F296C" },
    { "RLOADER", "Dodge W-Series '41" },
    { "SAVAGE", "Mil Mi-24 'Hind'" },
    { "SCORCHER", "Saracen Zen" },
    { "SCRAP", "Ford F-550 Rollback" },
    { "SHERIFF", "Ford Crown Victoria (Sheriff)" },
    { "SHERIFF2", "Chevrolet Suburban (Sheriff)" },
    { "SKYLIFT", "S-64 Skycrane" },
    { "SPARROW", "Bell H-13 Sioux" },
    { "SPARROW2", "Bell H-13 Sioux" },
    { "SPARROW3", "Bell H-13 Sioux" },
    { "STARLING", "Messerschmitt Me 163 Komet" },
    { "STRIKEFORCE", "A-10 Thunderbolt II" },
    { "STUNT", "Zivko Edge 540" },
    { "SUBMERS", "PC-1204 'Clelia'" },
    { "SUBMERS2", "Triton 1000/3" },
    { "TAXI", "Ford Crown Victoria Taxi" },
    { "TIPTRUCK2", "Ford L8000 Dump Truck" },
    { "TITAN", "Lockheed C-130 Hercules" },
    { "TITAN2", "Lockheed AC-130 Spectre" },
    { "TOURBUS", "LA City Tours Bus" },
    { "TOWTRUCK", "Chevrolet C-Series Wrecker" },
    { "TRACTOR", "Farmall Cub Tractor" },
    { "TRASH", "Mack LE Refuse Collection Truck" },
    { "TRIBIKE", "Whippet Race Bike" },
    { "TRIBIKE2", "Endurex Race Bike" },
    { "TRIBIKE3", "Tri-Cycles Race Bike" },
    { "TRSMALL2", "M51 Trailer Mount" },
    { "TUG", "Cape Romain Tug" },
    { "UTILTRUC", "Ford F-450 Utility" },
    { "VALKYRI2", "Bell UH-1Y Venom MOD.0" },
    { "VALKYRIE", "Bell UH-1Y Venom" },
    { "VELUM", "Piper PA-46 Malibu Meridian" },
    { "VELUM2", "Piper PA-46 Malibu Meridian (5-Seater)" },
    { "VETIR", "Renault TRM-4000" },
    { "VIGILANTE", "Batmobile" },
    { "VOLATOL", "Avro Vulcan" },
    { "VOMFEUER", "" },

}

local weapons = {
    { "WT_SG_ASL", "UTAS UTS-15" },
    { "WT_SG_PMP", "Mossberg 590" },
    { "WT_SG_PMP2", "Remington 870" },
    { "WT_SG_SOF", "Mossberg 500 (Shortened)" },
    { "WT_SG_BLP", "Kel-Tec KSG" },
    { "WT_CMBSHGN", "Franchi SPAS-12" },
    { "WT_MUSKET", "Brown Bess" },
    { "WT_HVYSHGN", "Saiga 12K" },
    { "WT_DBSHGN", "Zabala Sawed-Off Shotgun" },
    { "WT_AUTOSHGN", "Atchisson AA-12" },
    { "WT_GL", "M32 Milkor MGL" },
    { "WT_RPG", "NPO Bazalt RPG-7" },
    { "WT_MINIGUN", "M134 Minigun" },
    { "WT_RAILGUN", "ARC-920" },
    { "WT_HOMLNCH", "FIM-92 Stinger" },
    { "WT_CMPGL", "M79 Sawed-Off" },
    { "WT_GNADE", "M61 Grenade" },
    { "WT_GNADE_STK", "C-4" },
    { "WT_PETROL", "Kraftstoff 20L" },
    { "WT_SNIP_RIF", "AI Arctic Warfare" },
    { "WT_SNIP_HVY", "Barrett M107A1" },
    { "WT_SNIP_HVY2", "Serbu BFG-50A" },
    { "WT_MKRIFLE", "M39 EMR" },
    { "WT_MKRIFLE2", "Springfield M1A Loaded" },
    { "WT_UNARMED", "Fists" },
    { "WT_COMBATPDW", "SIG MPX" },
    { "WT_MG", "PKM" },
    { "WT_MG_CBT", "M249" },
    { "WT_MG_CBT2", "M60E4" },
    { "WT_GUSNBRG", "M1928A1 Thompson" },
    { "WT_RIFLE_ASL", "Type 56-2" },
    { "WT_RIFLE_ASL2", "AK-12" },
    { "WT_RIFLE_CBN", "H&K 416" },
    { "WT_RIFLE_CBN2", "Remington R5 RGP" },
    { "WT_RIFLE_ADV", "Tavor TAR-21" },
    { "WT_SPCARBINE", "H&K G36C" },
    { "WT_SPCARBINE2", "H&K G36K" },
    { "WT_PIST", "Taurus PT92AF" },
    { "WT_PIST2", "Beretta M9A3" },
    { "WT_PIST_CBT", "H&K P2000" },
    { "WT_PIST_50", "FN Five-seven" },
    { "WT_SNSPISTOL", "Heckler & Koch P7M10" },
    { "WT_SNSPISTOL2", "AMT Backup" },
    { "WT_HVYPISTOL", "Enterprise Wide Body 1911" },
    { "WT_VPISTOL", "FN Model 1922" },
    { "WT_MKPISTOL", "Thompson/Center Contender G2" },
    { "WT_REVOLVER", "ASG Dan Wesson" },
    { "WT_REVOLVER2", "Chiappa Rhino" },
    { "WT_REV_DA", "Colt M1892" },
    { "WT_PIST_AP", "Colt SCAMP" },
    { "WT_SMG_MCR", "IMI Mini Uzi" },
    { "WT_MCHPIST", "TEC-9" },
    { "WT_MINISMG", "Skorpion Vz. 61" },
    { "WT_SMG", "MP5A3" },
    { "WT_SMG2", "SIG Sauer MPX" },
    { "WT_SMG_ASL", "FN P90" },
    { "WT_BULLRIFLE", "QBZ-95" },
    { "WT_BULLRIFLE2", "VHS-2" },
    { "WT_CMPRIFLE", "AKS-74U" },
}

local root = menu.my_root()

menu.divider(root, "Real-life names")

menu.action(root, "Apply vehicle names", {"rcn"}, "Replace vehicle labels with real-life counterparts. Takes a few seconds.", function()
    util.toast("Applying vehicle names...")
    util.yield()
    apply_labels(cars)
    util.toast("Vehicle names applied.")
end)

menu.action(root, "Apply weapon names", {"rwn"}, "Replace weapon labels with real-life counterparts.", function()
    util.toast("Applying weapon names...")
    apply_labels(weapons)
    util.toast("Weapon names applied.")
end)

menu.divider(root, "Restore vanilla names")

local restore = menu.list(root, "Restore defaults", {"rndef"}, "Remove the custom labels and return to Rockstar names.")

menu.action(restore, "Restore vehicle names", {"dcn"}, "Remove real vehicle names.", function(click_type)
    menu.show_warning(restore, click_type, "Restore vanilla vehicle names?", function()
        util.toast("Restoring vehicle names...")
        remove_labels(cars)
        util.toast("Vehicle names restored.")
    end, function()
        util.toast("Cancelled.")
    end, false)
end)

menu.action(restore, "Restore weapon names", {"dwn"}, "Remove real weapon names.", function(click_type)
    menu.show_warning(restore, click_type, "Restore vanilla weapon names?", function()
        util.toast("Restoring weapon names...")
        remove_labels(weapons)
        util.toast("Weapon names restored.")
    end, function()
        util.toast("Cancelled.")
    end, false)
end)

menu.divider(root, "Version 4.0.0")

if not SCRIPT_SILENT_START then
    util.toast("Real Names loaded. Use Apply vehicle names (rcn).")
end
